"""Alembic migration script template."""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2975057382ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trade', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=True),
    sa.Column('overall_status', sa.String(length=1), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('trade', sa.String(length=30), nullable=False),
    sa.Column('scheduled_start', sa.Date(), nullable=False),
    sa.Column('scheduled_end', sa.Date(), nullable=True),
    sa.Column('assigned_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('andon_status', sa.String(length=1), nullable=False),
    sa.Column('last_touch_ts', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cleanup_confirmed', sa.Boolean(), nullable=False),
    sa.Column('readiness_lead_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=True),
    sa.Column('schedule_item_id', sa.UUID(), nullable=True),
    sa.Column('trade', sa.String(length=30), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('original_media_url', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=1), nullable=True),
    sa.Column('triggered_by', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('sender_email', sa.String(length=200), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedule_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_house', 'events', ['house_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_events_ts', 'events', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('designer_forwarding_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('designer_contact_id', sa.UUID(), nullable=True),
    sa.Column('forwarded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fallback_to_pm', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['designer_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('designer_forwarding_log')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index('idx_events_ts', table_name='events')
    op.drop_index('idx_events_house', table_name='events')
    op.drop_table('events')
    op.drop_table('schedule_items')
    op.drop_table('houses')
    op.drop_table('contacts')
    # ### end Alembic commands ###
